Update mesh.md with topology and geometry example
JuliaGeometry/Meshes.jl pull request #165
Opened 2021-08-16 08:02 UTC by moyner

Extending the existing example with boundary+coboundary and basic geometry.

2021-08-16 14:00 UTC, juliohm requested changes
Thank you @moyner for this great addition. Please consider this first round of reviews. Maybe it would make sense to start the example with a preamble text explaining what the example is about.

2021-08-16 14:00 UTC, juliohm commented on docs/src/meshes.md
> +# Convert topology to half edge topology for fast lookup
```suggestion
# convert topology to half-edge topology for fast lookup
```

2021-08-16 14:00 UTC, juliohm commented on docs/src/meshes.md
> +# and the lower dimension we are mapping to.
Convert this to normal text in between example code sections.

2021-08-16 14:00 UTC, juliohm commented on docs/src/meshes.md
> +b = Boundary{2,1}(ht)
I would use the symbol `\partial21` for the boundary relation so that it is explicit in the variable name.

2021-08-16 14:00 UTC, juliohm commented on docs/src/meshes.md
> +cb = Coboundary{1, 2}(ht)
Similarly, I would use `\scrC11` for the variable name to make the relation explicit in the variable name.

2021-08-20 10:21 UTC, juliohm commented
@moyner did you have a chance to take a look at this?

2021-09-06 23:32 UTC, juliohm commented
Fixed on master.

2021-09-06 23:32 UTC, closed without merging

2021-09-07 13:29 UTC, moyner commented
Thank you for fixing this. Sorry for not following up this PR.