CartesianGrid with offset methods
JuliaGeometry/Meshes.jl pull request #208
Opened 2021-11-16 04:48 UTC by ErickChacon

This adds the feature requested in #201. It basically extends the `CartesianGrid` with fields `dims`, `reference`,
`spacing`, and `offset`. The reason we include `reference` and `offset` is to be able to compute all vertices with respect to `reference` such as the n-dimensional vertex `i` is computed as:
```
reference .+ (i .- offset) .* spacing
```

## What has changed?

Most of previous functionality have not changed for the default value `offset = ntuple(i->1, Dim)`. However, it differs from how subsetting is done. In this PR, subsetting is done using the same `reference`  for the subgrid, this ensures that the vertices are numerically the same between the original grid and the subgrid.

The ideas behind this extension come from `StepRangeLen`; however, we allow the offset to be lower than 1 (this is necessary for the functionality of subgrids). See the image below, for example, where the `offset` corresponding to the subgrid has elements lower than 1.

```julia
using Meshes
using Plots
g = CartesianGrid((10, 10), Point(0.0, 0.0), Vec(1.0, 1.0), Vec(0, 0))
plot(g, label = "grid")
plot!(g[2:5, 3:6], lc = :blue, label = "subgrid")
plot!(Point(0.0, 0.0), color = :red, label = "reference", legend = true)
(g[2:5, 3:6]).offset
# 2-element SVector{2, Int64} with indices SOneTo(2):
#   0
#   -1
```

![subgrid](https://user-images.githubusercontent.com/7862458/141914730-ed174b6b-bbce-4ca4-aa0a-c57558bd59bd.png)

One current funny (maybe useful?) behavior of subgrids is that it is not restricted to the dimensions of the grid. I am not sure if this worked like that previously (it probably did). The interesting part is that way you are creating grids where the common vertices are exactly the same. Not sure if it is a desirable behavior, but happy to put restrictions on the `getindex` function.

```julia
using Meshes
using Plots
g = CartesianGrid((10, 10), Point(0.0, 0.0), Vec(1.0, 1.0), Vec(1, 1))
plot(g, label = "grid")
plot!(g[-1:12, 3:9], lc = :blue, label = "subgrid")
plot!(Point(0.0, 0.0), color = :red, label = "reference", legend = true)
```

![subgrid2](https://user-images.githubusercontent.com/7862458/141922555-3de7f2d3-a5ad-46d5-bd6a-b40ac1e11661.png)

## Additional notes:
- Using the term `origin` instead of `reference` might be also fine. Happy to put it back.
- I was not sure if we need to change the `show` method. For now, I was also printing `reference` to check the functionality of subgrids.

2021-11-16 11:42 UTC, juliohm commented
Thanks for preparing these examples with plots in the PR, they help a lot the review 🙏🏽 

Please let me know when the PR is ready for review and I will take a look. Currently it is failing some tests, and the code seems to contain commented lines you used during development.

2021-11-16 18:57 UTC, ErickChacon commented
The plots are useful for me too. There was only one commented line which is already removed. I will check the tests that are failing, it mainly seems to be related to subgrids (as I mention the way it works has changed). I will let you know when this PR is ready for review.

2021-11-18 00:56 UTC, ErickChacon commented
Hi @juliohm. I think this PR is ready for review. Please take into consideration the following notes.

As mentioned above, the main idea behind extending the `CartesianGrid` type is to be able to build grids where the vertices are comparable. We can achieve this by using a `reference` and `offset` argument such as the vertex associated to the `CartesianIndex` `i` is computed as:
```
reference .+ (i .- offset) .* spacing.
```

Before accepting this PR, there are some considerations we should agree on:

## Constructors

Right now, the more basic constructor uses the arguments `dims`, `origin` and `spacing`. Our extension uses `dims`, `reference`, `spacing` and `offset`. Initially, I was adding the `offset` argument to all type of constructors but I think that the user interested on this feature will want to work with the basic constructor because it allows control over `reference` and `offset`. Other constructors using `offset` are possible but that will be rarely used, so I am defining `offset=SVector(ntuple(i->1, Dim)` for other constructors.

## Offset values

The function `StepRangeLen` have the following restriction `1 ≤ offset ≤ n`. Putting a similar restriction for grids might not be adequate because it does not allow subsetting a grid keeping the same `reference` value.

See below some examples to understand the `offset` behaviour.

```julia
# CartesianGrid with default offset
g = CartesianGrid((10, 10), Point(0.0, 0.0), Vec(1.0, 1.0))
plot(g, label = "grid")
plot!(g.reference, c = :red, label = "reference", legend = true)
```

![offset-default](https://user-images.githubusercontent.com/7862458/142313507-338d0229-fd9f-4b9e-8a12-f1292b22ff2a.png)

```julia
# CartesianGrid with positive offset
g = CartesianGrid((10, 10), Point(0.0, 0.0), Vec(1.0, 1.0), Vec(4, 3))
plot(g, label = "grid")
plot!(g.reference, c = :red, label = "reference", legend = true)
```

![offset-positive](https://user-images.githubusercontent.com/7862458/142313727-24f01d9e-c149-4afb-9ebf-5cb57921a981.png)

```julia
# CartesianGrid with negative offset
g = CartesianGrid((10, 10), Point(0.0, 0.0), Vec(1.0, 1.0), Vec(-2, -1))
plot(g, label = "grid")
plot!(g.reference, c = :red, label = "reference", legend = true)
```

![offset-negative](https://user-images.githubusercontent.com/7862458/142313833-7ab4cafd-2670-48a3-a862-ea67d3a07437.png)

## Subsetting

As mentioned previously, I modified the subsetting behaviour in order to have subgrids where the vertices are comparable with the original behaviour. This basically means than the `reference` value should be the same for the original grid and the subgrid. The only arguments that should change are the `offset` and `dims` attributes. Is this a desirable approach or do we prefer the previous implementation approach where, in practice, the common vertices are not numerically the same?

The subsetting approach of this PR allows the new grid to not be limited to the domain of the original grid. Should we put a restriction? I did not put any restriction and the behaviour can be understood from the initial description of the PR.

## Equivalence

Currently, we consider two grids to be the same if the `dims`, `origin` and `spacing` attributes are the same. In theory, this is right but not in practice because the vertices will not be numerically the same because we are using different `origins`. For now, I am considering that two grids are equivalent if the `dims`, `reference`, `spacing` and `offset` are the same, this means that two grids will be equivalent if the vertices created will also be numerically the same. For this reason, I had to modify some tests in order to define the right `CartesianGrid` object to compare with. Again, is this the desired behaviour? Or do we prefer the previous behaviour where grids are still equivalent even if the vertices are not numerically the same?

2021-11-19 19:42 UTC, juliohm commented
@ErickChacon I will try to find some time next week to review this. Really busy around here finishing up some projects, but I will come back to this at some point. 🙏🏽

2021-12-14 11:37 UTC, juliohm commented
@ErickChacon sorry for not having had the time to review your PR yet. I've released a minor version of the project with a few breaking changes and improvements and the plan is to incorporate your PR and fixes to #54 in the next minor release.

I will ping you in January so that we can work together on updating the PR to the latest master branch, and the latest release of the language.

2021-12-15 15:15 UTC, ErickChacon commented
Hi @juliohm. no problem at all. Happy to work on this in January.

2022-04-22 14:53 UTC, juliohm commented
Hi @ErickChacon any chance you can revive this PR in the following weeks? We are planning a next minor release and it would be nice to have this generalization you proposed.

2022-04-25 19:55 UTC, juliohm commented
Closing it as inactive. Feel free to start a fresh PR based on the latest master branch.

2022-04-25 20:33 UTC, ErickChacon commented
Hi @juliohm. Sorry for the late reply, I was a bit busy these days. Sure, I would be happy to revive this PR.  Can I get your feedback about the comments I did above with respect to *constructors*, *offset values*, *subsetting* and *equivalence* so I am sure how to proceed? Are you sure you want me to create another PR or just update this one? Cheers.

2022-04-26 11:09 UTC, juliohm commented
Hi @ErickChacon we can update this PR, no worries. I will take a look at the comments now.

2022-04-26 11:16 UTC, juliohm requested changes
Hi @ErickChacon I appreciate if you can undo the `origin` -> `reference` change. This will clean up the PR and will highlight only the meaningful changes. The word `origin` is still appropriate if I understand your proposal correctly.

2022-04-26 11:16 UTC, juliohm commented on src/mesh/cartesiangrid.jl
> +    CartesianGrid(dims, reference, spacing)
Can we stick to the name origin to reduce the amount of changes in the docstrings and code? I believe the meaning of the variable is still the same right? You are only adding a new offset argument to the algorithms.

2022-04-26 11:16 UTC, juliohm commented on src/mesh/cartesiangrid.jl
> +  CartesianGrid{Dim,T}(dims, start, spacing, SVector(ntuple(i->1, Dim)))
Please define the offset variable outside the constructor for improved readability.

2022-04-26 11:16 UTC, juliohm commented on src/mesh/cartesiangrid.jl
> +  CartesianGrid{Dim,T}(dims, start, (finish - start) ./ dims, SVector(ntuple(i->1, Dim)))
Please define offset variable outside constructor.

2022-04-26 11:16 UTC, juliohm commented on src/mesh/cartesiangrid.jl
> +  CartesianGrid{Dim,T}(dims, ntuple(i->zero(T), Dim), ntuple(i->one(T), Dim), ntuple(i->1, Dim))
Same here.

2022-04-27 04:12 UTC, ErickChacon commented
This is still work in progress. @juliohm, I will let you know when I think this is ready for review.

2022-04-28 13:40 UTC, ErickChacon commented
Hi @juliohm. This pull request is ready to be reviewed. Cheers.

2022-05-03 00:41 UTC, juliohm commented on test/partitioning.jl
> +    @test s == CartesianGrid((9,9), P2(0,0), V2(1,1), (0,0))
Hi @ErickChacon before I start reviewing the PR, could you please explain why some of these old tests are being touched? I had understood that the addition of the new `offset` field should be backward compatible?

2022-05-03 00:43 UTC, juliohm commented on src/mesh/cartesiangrid.jl
> +  offset::NTuple{Dim,Int}
Should this be offset::Dims{Dim} ?

2022-05-03 00:44 UTC, juliohm commented
Hi @ErickChacon appreciate if you can clarify some of the questions I left above. Also, could you please add new tests for the expected usage of the new offset field?

2022-05-04 14:19 UTC, ErickChacon commented on test/partitioning.jl
> +    @test s == CartesianGrid((9,9), P2(0,0), V2(1,1), (0,0))
Hi @juliohm. I forgot to change these tests back . Previously, they were failing because of the definition of `==`. However, I also extended this more accordingly with the use of offset. I will change back these old tests.

2022-05-04 14:20 UTC, ErickChacon commented on src/mesh/cartesiangrid.jl
> +  offset::NTuple{Dim,Int}
Agree with that.

2022-05-04 20:30 UTC, juliohm requested changes
Nice @ErickChacon , can you please add tests now for the new constructor?

Also, did you have a chance to benchmark this change against the master branch? For example, constructing a `grid = CartesianGrid(1000,1000)` and collecting the elements with collect(grid) would call the new expressions involving grid.offset

2022-05-04 20:30 UTC, juliohm commented on src/mesh/cartesiangrid.jl
> +  CartesianGrid{Dim,T}(dims, start, (finish - start) ./ dims, offset)
```suggestion
  origin  = start
  spacing = (finish - start) ./ dims
  offset  = ntuple(i->1, Dim)
  CartesianGrid{Dim,T}(dims, origin, spacing, offset)
```

2022-05-04 20:30 UTC, juliohm commented on src/mesh/cartesiangrid.jl
> +  CartesianGrid{Dim,T}(dims, ntuple(i->zero(T), Dim), ntuple(i->one(T), Dim), offset)
```suggestion
  origin  = ntuple(i->zero(T), Dim)
  spacing = ntuple(i->one(T), Dim)
  offset  = ntuple(i->1, Dim)
  CartesianGrid{Dim,T}(dims, origin, spacing, offset)
```

2022-05-04 20:30 UTC, juliohm commented on src/mesh/cartesiangrid.jl
> +  g1.origin - g2.origin == (g1.offset .- g2.offset) .* g1.spacing
Nice generalization 👍🏽

2022-05-05 03:34 UTC, ErickChacon commented
> Nice @ErickChacon , can you please add tests now for the new constructor?


I added tests for (i) the constructor,  (ii) subgrids with comparable vertices with respect to the original grid (which is a new feature thank to the offset behaviour), and (iii) expanding a CartesianGrid where the vertices are comparable. Feel free to suggest to remove the test (iii). In general, the inclusion of the `offset` allow us to create grids, subgrids or intersecting grids where the vertices and elements are numerically comparable.

> Also, did you have a chance to benchmark this change against the master branch? For example, constructing a `grid = CartesianGrid(1000,1000)` and collecting the elements with collect(grid) would call the new expressions involving grid.offset

I think this PR should not create additional computational cost because the master branch is using implicitly an `offset = (1,1)`.  In some cases, I just had to change the expression `.- 1` to `.- offset`. See below an benchmark example.

```julia
using BenchmarkTools
using Meshes

grid = CartesianGrid(1000,1000)
@benchmark a = collect(grid)

# CartessianGrid branch:
# BenchmarkTools.Trial: 16 samples with 1 evaluation.
#  Range (min … max):  161.654 ms … 404.918 ms  ┊ GC (min … max):  0.00% … 58.44%
#  Time  (median):     323.978 ms               ┊ GC (median):    49.38%
#  Time  (mean ± σ):   316.144 ms ±  50.887 ms  ┊ GC (mean ± σ):  47.98% ± 12.82%
#
#                                      █     ██
#   ▇▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▇▇█▇▁▁▇▁██▁▁▁▁▁▁▁▁▁▁▁▁▁▇▁▁▁▇ ▁
#   162 ms           Histogram: frequency by time          405 ms <
#
#  Memory estimate: 389.10 MiB, allocs estimate: 7000012.

# Master branch:
# BenchmarkTools.Trial: 16 samples with 1 evaluation.
#  Range (min … max):  161.936 ms … 418.074 ms  ┊ GC (min … max):  0.00% … 57.95%
#  Time  (median):     330.737 ms               ┊ GC (median):    50.60%
#  Time  (mean ± σ):   333.634 ms ±  57.050 ms  ┊ GC (mean ± σ):  49.27% ± 13.42%
#
#                                          █▃
#   ▇▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▇▁▁▁▁▇▁▁▁▇██▁▇▁▁▇▇▁▇▁▁▁▁▇▁▁▇▁▁▁▇ ▁
#   162 ms           Histogram: frequency by time          418 ms <
#
#  Memory estimate: 389.10 MiB, allocs estimate: 7000012.
#

```

2022-05-05 16:34 UTC, juliohm commented on src/mesh/cartesiangrid.jl
> +  CartesianGrid{Dim,T}(dims, start, spacing, offset)
```suggestion
  origin = start
  offset = ntuple(i->1, Dim)
  CartesianGrid{Dim,T}(dims, origin, spacing, offset)
```

2022-05-05 16:35 UTC, juliohm commented on src/mesh/cartesiangrid.jl
> +  newoffset = g.offset .- first(I).I .+ 1
```suggestion
  offset = g.offset .- first(I).I .+ 1
```

2022-05-05 16:36 UTC, juliohm commented on src/mesh/cartesiangrid.jl
> +  CartesianGrid(dims, g.origin, g.spacing, newoffset)
```suggestion
  CartesianGrid(dims, g.origin, g.spacing, offset)
```

2022-05-05 16:36 UTC, juliohm commented on src/mesh/cartesiangrid.jl
>    dims   = size(I)
```suggestion
  dims   = size(I)
  offset = g.offset .- first(I).I .+ 1
```

2022-05-05 16:39 UTC, juliohm commented on test/mesh.jl
> +    grid2 = CartesianGrid(newdim, grid.origin, grid.spacing, newoffset)
```suggestion
    grid2 = CartesianGrid(newdim, origin(grid), spacing(grid), newoffset)
```

2022-05-05 16:40 UTC, juliohm commented on test/mesh.jl
> +    right = (1,1)
```suggestion
    left, right = (1,1), (1,1)
```

2022-05-05 16:40 UTC, juliohm approved these changes
That is really nice work @ErickChacon , thank you for the generalization. I did minor adjustments to the PR and will just wait the tests to pass.

2022-05-05 16:55 UTC, juliohm commented on test/mesh.jl
> +    grid2 = CartesianGrid(newdim, origin(grid), spacing(grid), newoffset)
```suggestion
    grid2 = CartesianGrid(newdim, minimum(grid), spacing(grid), newoffset)
```

2022-05-05 16:56 UTC, juliohm commented on test/mesh.jl
> +    newoffset = grid.offset .+ left
```suggestion
    newdim = size(grid) .+ left .+ right
    newoffset = offset(grid) .+ left
```

2022-05-05 16:56 UTC, juliohm commented on src/mesh/cartesiangrid.jl
>  spacing(g::CartesianGrid) = g.spacing
```suggestion
spacing(g::CartesianGrid) = g.spacing
offset(g::CartesianGrid) = g.offset
```

2022-05-05 17:14 UTC, ErickChacon commented
Hi @juliohm. Happy with the changes you did! Let me know in case we need something else.

2022-05-05 17:47 UTC, merged