Master
JuliaGeometry/Meshes.jl pull request #330
Opened 2022-11-21 00:23 UTC by Veenty

Added simple example to the docs
Fixed error in topology docs (doubly periodic topology corresponds to a torus, not a sphere)

2022-11-21 11:32 UTC, juliohm requested changes
@Veenty please work more on this PR, it is not ready. Move the example to the section where we discuss SimpleMesh and provide examples. Then consider sharing your intentions with the reader otherwise the example comes as a surprise without context.

2022-11-21 11:32 UTC, juliohm commented on docs/src/meshes.md
> +```
This example is placed in the wrong section of the documentation. Please follow the code style in the docs and try to provide additional explanation for what is happening.

2022-11-25 11:14 UTC, juliohm commented
@Veenty did you have time to take a look into this?

2022-11-25 14:49 UTC, Veenty commented
Yes, I’ll add more detail and change the section over the weekend!

On Fri, Nov 25, 2022 at 6:14 AM Júlio Hoffimann ***@***.***>
wrote:

> @Veenty <https://github.com/Veenty> did you have time to take a look into
> this?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/JuliaGeometry/Meshes.jl/pull/330#issuecomment-1327346541>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGIE7DLV5GCXCUDDQQLGDSDWKCNSDANCNFSM6AAAAAASGDLHGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-01 10:41 UTC, juliohm commented on docs/src/meshes.md
> +```
@Veenty please erase this example

2022-12-01 10:41 UTC, juliohm commented on src/mesh/simplemesh.jl
> +
```suggestion
```

2022-12-01 10:42 UTC, juliohm commented on src/mesh/simplemesh.jl
> +viz(mesh_noisy)
please follow the code style of the other examples nearby. We do not use underscores, the name vertex is singular but the variable stores a list of vertices, ...

2022-12-05 21:41 UTC, closed without merging