add measure to Cylinder and CylinderSurface
JuliaGeometry/Meshes.jl pull request #334
Opened 2022-12-04 21:37 UTC by dorn-gerhard

2022-12-04 21:40 UTC, juliohm requested changes
Awesome. We are only missing tests.

2022-12-05 11:47 UTC, dorn-gerhard commented
I added tests for measure of Cylinder and CylinderSurface

2022-12-05 11:49 UTC, juliohm commented on src/primitives/cylinder.jl
> +measure(c::Cylinder) = norm(origin(c.bot) - origin(c.top)) * c.radius^2 * pi
```suggestion
measure(c::Cylinder) = norm(origin(c.bot) - origin(c.top)) * c.radius^2 * pi

volume(c::Cylinder) = measure(c)
```

2022-12-05 11:49 UTC, juliohm commented on src/primitives/cylindersurface.jl
> +measure(c::CylinderSurface) = (norm(origin(c.bot) - origin(c.top)) + c.radius) * 2 * c.radius * pi
```suggestion
measure(c::CylinderSurface) = (norm(origin(c.bot) - origin(c.top)) + c.radius) * 2 * c.radius * pi

area(c::CylinderSurface) = measure(c)
```

2022-12-05 11:51 UTC, juliohm commented on test/primitives.jl
> +    @test measure(c) ≈ T(5)^2 * pi * T(3)*sqrt(T(3))
```suggestion
    @test measure(c) == volume(c) ≈ T(5)^2 * pi * T(3)*sqrt(T(3))
```

2022-12-05 11:51 UTC, juliohm commented on test/primitives.jl
> +    @test measure(c) ≈ pi
```suggestion
    @test measure(c) == volume(c) ≈ pi 
```

2022-12-05 11:52 UTC, juliohm commented on test/primitives.jl
> +    @test measure(c) ≈ 2 * T(5)^2 * pi + 2 * T(5) * pi * sqrt(3*T(3)^2)
```suggestion
    @test measure(c) == area(c) ≈ 2 * T(2)^2 * pi + 2 * T(2) * pi 

    c = CylinderSurface(T(5),
                 Plane(P3(1,2,3), V3(0,0,1)),
                 Plane(P3(4,5,6), V3(0,0,1)))
    @test measure(c) == area(c) ≈ 2 * T(5)^2 * pi + 2 * T(5) * pi * sqrt(3*T(3)^2)
```

2022-12-05 12:47 UTC, merged