Implement Ray-Plane intersection type and algorithm
JuliaGeometry/Meshes.jl pull request #339
Opened 2022-12-16 02:34 UTC by jackbeagley

Added appropriate types for Ray-Plane intersections, mostly taken from Segment-Plane intersections. Same tests added and used too, main difference is that rays extend past λ=1.

2022-12-16 15:25 UTC, juliohm requested changes
Review attached.

2022-12-16 15:25 UTC, juliohm commented on src/intersections/rayplane.jl
> +    ln = r.v ⋅ n
Please use the public API to get the vector of the ray

2022-12-16 15:25 UTC, juliohm commented on src/intersections/rayplane.jl
> +        if isapprox(coordinates(pₒ - r.p) ⋅ n, zero(T), atol=atol(T))
public api for r.p

2022-12-16 15:25 UTC, juliohm commented on src/intersections/rayplane.jl
> +        λ = -(n ⋅ coordinates(r.p - pₒ)) / ln
same here

2022-12-16 15:25 UTC, juliohm commented on src/intersections/rayplane.jl
> +        end
incorrect indentation, please use the 2-space indentation style of the project

2022-12-16 21:28 UTC, jackbeagley commented
> Review attached.

Thanks for those points @juliohm , I have just fixed them!

2022-12-17 11:30 UTC, juliohm commented on src/intersections/rayplane.jl
> +function Meshes.intersection(f, r::Ray{3,T}, p::Plane{T}) where {T}
```suggestion
function intersection(f, r::Ray{3,T}, p::Plane{T}) where {T}
```

2022-12-17 11:34 UTC, juliohm commented
@jackbeagley you mean that this PR is a copy of the existing segment-plane code plus the additional flexibility to allow t>1? If that is the case we need to refactor the existing code to avoid duplication instead. We don't want to maintain to functions that are exactly the same with the exception of one line or so.

2022-12-17 20:42 UTC, jackbeagley commented
> @jackbeagley you mean that this PR is a copy of the existing segment-plane code plus the additional flexibility to allow t>1? If that is the case we need to refactor the existing code to avoid duplication instead. We don't want to maintain to functions that are exactly the same with the exception of one line or so.

Yes... that is a good point. Let me have a go at refactoring it and using this method we should get Lines for free too!

2022-12-23 14:17 UTC, juliohm commented
@jackbeagley can we close this in favor of a fresh PR with the refactored version?

2022-12-23 20:13 UTC, closed without merging