Fix GSLIB convention
JuliaGeometry/Meshes.jl pull request #45
Opened 2021-02-18 20:25 UTC by rmcaixeta

This fixes #44 
It was quick, so I made it today
The `reverse` call was ok for 2D, but need to be adjusted for 3D as just X-Y are swapped
I also migrated the rotation convention tests to check if the others were ok and it seems fine

2021-02-18 20:40 UTC, rmcaixeta commented
But it seems that this `reverse(A, start, stop)` approach is only possible if `A` is an `AbstractArray`. It doesn't work for `Tuples`. Any suggestion?

2021-02-18 21:22 UTC, juliohm requested changes
Thank you for the quick fix @rmcaixeta ! That helps a lot 💯 

Besides moving the test, we need to fix the reverse for tuples. Perhaps writing it as you did in the previous version with `semiaxes[2], semiaxes[1]` to create the reverse would be fine?

It is good to know I didn't mess up the algorithm in the migration.

2021-02-18 21:22 UTC, juliohm commented on test/conventions.jl
> +@testset "Conventions" begin
That is awesome, thanks for the additional tests! ❤️ Could you move them to the test/neighborhood.jl file together with the other tests of similar nature? We have an open issue regarding these conventions that may justify a separate test/conventions.jl file in the future: #43

2021-02-18 21:38 UTC, rmcaixeta commented
Ok. I'll move the tests tomorrow

About the tuple issue, the last approach wouldn't work either because I'd need to modify the tuple. In GeoStatsBase it was constrained to AbstractVector I guess

Better create a new tuple on those cases or constrain the input to Vectors?

2021-02-18 21:44 UTC, juliohm commented
Let's create a new tuple then. In Meshes.jl we are supporting static arguments as inputs consistently (tuples of coordinates).

2021-02-19 00:39 UTC, juliohm commented
I think the cleanest solution would be to assume vectors in this outer constructor and then provide an additional outer constructor that converts the tuples to vectors 👍🏽 That way we can use the convenient `reverse(v, 1, 2)` syntax.

2021-02-19 10:31 UTC, rmcaixeta commented
Waiting for the tests to check if everything's ok. Seems alright for you?

2021-02-19 10:36 UTC, juliohm requested changes
Nice trick with the list comprehension 💯

Can you just rearrange the tests in the same test set? :)

2021-02-19 10:36 UTC, juliohm commented on test/neighborhoods.jl
> +  @testset "RotationConvention" begin
I think we can remove the test set and place these tests immediately after the other tests and before the final tests with the `show` methods.

2021-02-19 10:36 UTC, juliohm commented on src/neighborhoods/ellipsoid.jl
> +  ranges = invert ? [semiaxes[i] for i in reverse(1:Dim,1,2)] : semiaxes
Nice trick!

2021-02-19 11:13 UTC, juliohm approved these changes
Amazing work as usual! Merging it.

2021-02-19 11:13 UTC, merged