Avoid using the `Polytope(::AbstractVector)` constructor
JuliaGeometry/Meshes.jl pull request #507
Opened 2023-07-13 16:27 UTC by eliascarv

### Note
The `Polytope(::AbstractVector)` constructors are commented out to check that tests will pass without them.
### Decision
Should we remove these constructors?

### Update 2023-07-13 18:00
It has been decided that the `Polytope(::AbstractVector)` constructors are no longer needed and can be removed.

2023-07-13 19:18 UTC, juliohm requested changes
Thank you @eliascarv , it looks great. Attached minor review.

Can you also provide a comparison in terms of speed and memory allocation compared to the master branch? Do we gain something with these replacements?

2023-07-13 19:18 UTC, juliohm commented on src/mesh.jl
> +  type(v)
```suggestion
  verts = ntuple(i -> cart2vert(g, cinds[einds[i]]), nvertices(type))
  type(verts)
```

2023-07-13 19:18 UTC, juliohm commented on src/polytopes/hexahedron.jl
> +  Hexahedron(v)
rename v --> verts

2023-07-13 20:14 UTC, eliascarv commented
## Benchmarks
Version info:

![image](https://github.com/JuliaGeometry/Meshes.jl/assets/73039601/8344b93e-91aa-4224-9d53-75b9acd3e31f)

### materialize
master:

![Captura de tela de 2023-07-13 17-09-54](https://github.com/JuliaGeometry/Meshes.jl/assets/73039601/692759f9-73dc-4242-b455-38357ad2c69d)

PR:

![image](https://github.com/JuliaGeometry/Meshes.jl/assets/73039601/e33bc5ef-e418-4a56-a111-f7fe96d998f4)

2023-07-13 20:33 UTC, juliohm commented on src/transforms.jl
> +  PL(v)
You can write this in one line as well, without the intermediate v variable.

2023-07-14 12:16 UTC, juliohm approved these changes
Awesome work @eliascarv. I believe this new internal representation in set of constructors will help us design the most performant algorithms at compile time.

2023-07-14 12:17 UTC, merged